// Front-end mirror of chat WebSocket events. Keep in sync with backend chat/events.ts
export const ChatEvents = {
  PING: "ping",
  PONG: "pong",
  ROOM_JOIN: "room.join",
  ROOM_JOINED: "room.joined",
  ROOM_LEAVE: "room.leave",
  ROOM_LEFT: "room.left",
  MESSAGE_SEND: "message.send",
  MESSAGE_NEW: "message.new",
  MESSAGE_SENT: "message.sent",
  MESSAGE_LIST: "message.list",
  MESSAGE_LOAD: "message.load",
  MESSAGE_EDIT: "message.edit",
  MESSAGE_UPDATED: "message.updated",
  MESSAGE_DELETE: "message.delete",
  MESSAGE_DELETED: "message.deleted",
  MESSAGE_DELIVERED: "message.delivered",
  MESSAGE_READ: "message.read",
  MESSAGE_ERROR: "message.error",
  CONVERSATION_LIST: "conversation.list",
  CONVERSATION_LIST_DATA: "conversation.list",
  CONVERSATION_CREATE: "conversation.create",
  CONVERSATION_CREATED: "conversation.created",
  CONVERSATION_UPDATED: "conversation.updated",
  CONVERSATION_TITLE_UPDATE: "conversation.title.update",
  PARTICIPANT_READ: "participant.read",
  TYPING_START: "typing.start",
  TYPING_STARTED: "typing.started",
  TYPING_STOP: "typing.stop",
  TYPING_STOPPED: "typing.stopped",
  ERROR: "error",
} as const;

export type ChatEvent = (typeof ChatEvents)[keyof typeof ChatEvents];
